---
- name: Configure db server
  hosts: dbservers
  become: yes
  vars_files:
    - passwords.yml
  vars:
    mysql_root_username: root
    mysql_db_name: task_12_db
    mysql_user_name: task-12-user
    mysql_user_password: task-12-password
  tasks:
    - name: Copy shell script
      copy:
        src: ./DatabaseServer/mysql-install.sh
        dest: /home/ec2-user/mysql-install.sh
        owner: root
        group: root
        mode: 0777

    - name: Run shell script
      shell: /home/ec2-user/mysql-install.sh

    - name: Install pip package manager
      dnf:
        name: python3-pip
        state: latest

    - name: Install pymysql module
      pip:
        name: pymysql
        state: latest
        executable: pip3

    - name: Create MySQL database
      mysql_db:
        name: "{{ mysql_db_name }}"
        state: present
        login_user: "{{ mysql_root_username }}"
        login_password: "{{ mysql_root_password }}"

    - name: Create User
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        name: "{{ mysql_user_name }}"
        password: "{{ mysql_user_password }}"
        priv: "{{ mysql_db_name }}.*:ALL"
        state: present