- name: Verify MySQL database connection
  hosts: webservers
  gather_facts: false
  become: true

  tasks:
    - name: Verify MySQL database connection
      wait_for:
        host: "{{ item }}"
        port: 3306  
        timeout: 5
      ignore_errors: true
      register: mysql_connection_status
      loop: "{{ groups['dbservers'] }}"

    - name: Print connection status
      debug:
        msg: "MySQL database connection {{ 'succeeded' if mysql_connection_status is success else 'failed' }}"