---
- name: Configure web server
  hosts: webservers
  become: yes
  tasks:
    - name: Install nginx server
      dnf:
        name: nginx
        state: latest
    - name: Start nginx server
      service:
        name: nginx
        state: started
    - name: Enable nginx server
      service:
        name: nginx
        enabled: yes